/**
 * OpenAI Service for Dream Analysis
 *
 * This service provides dream analysis functionality using OpenAI's GPT models.
 * It supports both real API calls and mock mode for development.
 *
 * Features:
 * - Structured dream analysis output
 * - Content safety validation
 * - Mock mode for development without API keys
 * - Configurable model parameters
 */

import OpenAI from 'openai';

// Types for dream analysis
export interface DreamAnalysisInput {
  dreamText: string;
  userId?: string;
  metadata?: {
    date?: string;
    mood?: string;
    tags?: string[];
  };
}

export interface DreamAnalysis {
  summary: string;
  themes: string[];
  emotions: string[];
  symbols: Array<{
    symbol: string;
    interpretation: string;
  }>;
  insights: string;
  disclaimer: string;
}

export interface DreamAnalysisResponse {
  analysis: DreamAnalysis;
  tokensUsed?: number;
  model?: string;
  isMock: boolean;
}

// Configuration
const config = {
  apiKey: process.env.OPENAI_API_KEY || '',
  model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
  maxTokens: parseInt(process.env.OPENAI_MAX_TOKENS || '2000', 10),
  temperature: parseFloat(process.env.OPENAI_TEMPERATURE || '0.7'),
  mockMode: process.env.MOCK_MODE === 'true',
};

// Initialize OpenAI client only if not in mock mode
let openaiClient: OpenAI | null = null;
if (!config.mockMode && config.apiKey) {
  openaiClient = new OpenAI({
    apiKey: config.apiKey,
  });
}

/**
 * Mock dream analysis generator
 * Provides realistic responses for development without API costs
 */
function generateMockAnalysis(dreamText: string): DreamAnalysis {
  const dreamLower = dreamText.toLowerCase();

  // Simple keyword-based mock analysis
  const hasWater = dreamLower.includes('water') || dreamLower.includes('ocean') || dreamLower.includes('river');
  const hasFlying = dreamLower.includes('fly') || dreamLower.includes('flying') || dreamLower.includes('float');
  const hasFear = dreamLower.includes('scared') || dreamLower.includes('fear') || dreamLower.includes('anxiety');
  const hasChase = dreamLower.includes('chase') || dreamLower.includes('running') || dreamLower.includes('escape');

  const themes: string[] = [];
  const emotions: string[] = [];
  const symbols: Array<{ symbol: string; interpretation: string }> = [];

  if (hasWater) {
    themes.push('Emotional depth and subconscious exploration');
    emotions.push('Reflective');
    symbols.push({
      symbol: 'Water',
      interpretation: 'Represents emotions, the unconscious mind, and life\'s flow. Clear water often indicates clarity of thought, while turbulent water may suggest emotional turmoil.',
    });
  }

  if (hasFlying) {
    themes.push('Freedom and transcendence');
    emotions.push('Liberated');
    symbols.push({
      symbol: 'Flying',
      interpretation: 'Often symbolizes a desire for freedom, rising above problems, or gaining a new perspective on life situations.',
    });
  }

  if (hasFear) {
    themes.push('Confronting fears and anxieties');
    emotions.push('Anxious', 'Apprehensive');
  }

  if (hasChase) {
    themes.push('Avoidance and confrontation');
    emotions.push('Stressed');
    symbols.push({
      symbol: 'Being chased',
      interpretation: 'May represent avoiding a situation, person, or aspect of yourself in waking life. Consider what you might be running from.',
    });
  }

  // Default themes if none detected
  if (themes.length === 0) {
    themes.push('Personal growth and self-discovery', 'Daily life reflection');
  }

  if (emotions.length === 0) {
    emotions.push('Contemplative', 'Curious');
  }

  if (symbols.length === 0) {
    symbols.push({
      symbol: 'Dream narrative',
      interpretation: 'Your dream contains unique personal symbolism that reflects your individual experiences and perspective.',
    });
  }

  return {
    summary: `This dream appears to explore ${themes[0].toLowerCase()}. The imagery and narrative suggest a processing of recent experiences and emotions.`,
    themes,
    emotions,
    symbols,
    insights: `Your dream reflects natural psychological processes of memory consolidation and emotional processing. The themes present in this dream may connect to current life circumstances or deeper patterns in your subconscious. Consider journaling about the emotions and symbols to gain further personal insights.`,
    disclaimer: 'This analysis is generated by AI and is meant for entertainment and self-reflection purposes only. It is not a substitute for professional psychological or medical advice.',
  };
}

/**
 * Content validation
 * Ensures dream text is appropriate for analysis
 */
function validateDreamContent(dreamText: string): { valid: boolean; error?: string } {
  if (!dreamText || typeof dreamText !== 'string') {
    return { valid: false, error: 'Dream text is required' };
  }

  const trimmed = dreamText.trim();
  if (trimmed.length < 10) {
    return { valid: false, error: 'Dream text must be at least 10 characters long' };
  }

  if (trimmed.length > 10000) {
    return { valid: false, error: 'Dream text must be less than 10,000 characters' };
  }

  return { valid: true };
}

/**
 * Analyze a dream using OpenAI's GPT models
 * Falls back to mock mode if API key is not configured
 */
export async function analyzeDream(
  input: DreamAnalysisInput
): Promise<DreamAnalysisResponse> {
  // Validate input
  const validation = validateDreamContent(input.dreamText);
  if (!validation.valid) {
    throw new Error(validation.error);
  }

  // Mock mode - no API call
  if (config.mockMode || !openaiClient) {
    console.log('[OpenAI Service] Running in mock mode');
    return {
      analysis: generateMockAnalysis(input.dreamText),
      isMock: true,
      model: 'mock',
    };
  }

  // Real API call to OpenAI
  try {
    const systemPrompt = `You are a knowledgeable dream analyst who provides thoughtful, balanced interpretations of dreams.

Your role is to:
- Identify common dream symbols and their potential meanings
- Recognize emotional themes and patterns
- Provide insights based on psychological dream theory
- Be respectful of the dreamer's personal experience
- Avoid making definitive claims about the dreamer's life
- Include appropriate disclaimers

Always remember that dream interpretation is subjective and should be used for self-reflection, not as definitive psychological analysis.`;

    const userPrompt = `Please analyze the following dream and provide a structured interpretation:

Dream: "${input.dreamText}"

${input.metadata?.mood ? `Mood when recording: ${input.metadata.mood}` : ''}
${input.metadata?.tags?.length ? `Tags: ${input.metadata.tags.join(', ')}` : ''}

Provide your analysis in the following JSON format:
{
  "summary": "A brief 2-3 sentence summary of the dream's main narrative",
  "themes": ["Theme 1", "Theme 2", "Theme 3"],
  "emotions": ["Emotion 1", "Emotion 2"],
  "symbols": [
    {
      "symbol": "Symbol name",
      "interpretation": "What this symbol might represent"
    }
  ],
  "insights": "Deeper psychological insights and patterns (2-3 sentences)",
  "disclaimer": "Standard disclaimer about the analysis being for self-reflection only"
}`;

    const response = await openaiClient.chat.completions.create({
      model: config.model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      response_format: { type: 'json_object' },
      max_tokens: config.maxTokens,
      temperature: config.temperature,
    });

    const content = response.choices[0]?.message?.content;
    if (!content) {
      throw new Error('No response from OpenAI');
    }

    const analysis = JSON.parse(content) as DreamAnalysis;

    // Ensure disclaimer is present
    if (!analysis.disclaimer) {
      analysis.disclaimer = 'This analysis is generated by AI and is meant for entertainment and self-reflection purposes only. It is not a substitute for professional psychological or medical advice.';
    }

    return {
      analysis,
      tokensUsed: response.usage?.total_tokens,
      model: response.model,
      isMock: false,
    };
  } catch (error) {
    console.error('[OpenAI Service] Error analyzing dream:', error);

    // Check for specific OpenAI errors
    if (error instanceof OpenAI.APIError) {
      if (error.status === 401) {
        throw new Error('Invalid OpenAI API key. Please check your configuration.');
      } else if (error.status === 429) {
        throw new Error('OpenAI rate limit exceeded. Please try again later.');
      } else if (error.status === 400) {
        throw new Error('Invalid request to OpenAI. The dream content may contain unsupported characters.');
      }
    }

    throw new Error(`Failed to analyze dream: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Check if the service is properly configured
 */
export function isConfigured(): boolean {
  return config.mockMode || (!!config.apiKey && config.apiKey.length > 0);
}

/**
 * Get service configuration (without exposing API key)
 */
export function getServiceInfo() {
  return {
    mockMode: config.mockMode,
    configured: isConfigured(),
    model: config.model,
    hasApiKey: !!config.apiKey && config.apiKey.length > 0,
  };
}
